development:
  adapter: postgresql
  encoding: utf8
  database: dubsoft_development
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: dubsoft_production
  pool: 5
  username: 
  password:

